
name: Mirror Airtable data

on:
  schedule:
    
  - cron: "0 8 * * *" #update every day at 8AM
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Install package manager for deps
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
        cache: "pipenv"
    - name: Install deps
      run: pipenv install
    - name: Make that mirror, please
      env:
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
        
        SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}

      run: pipenv run python mirror.py

  notify:
    runs-on: ubuntu-latest
    needs: 
      - scrape  # Ensure notification is sent after the scrape job
    if: ${{ failure() }} # Trigger only on failure

    steps:
      - name: Notify Discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.discord-failure-webhook }}
          username: 'GitHub Action Pipeline Failure Notification'
          avatar-url: ${{ secrets.avatar-url }}
          title: '${{ github.repository }}: {{Status}}'
          description: 'The repository ${{ github.repository }} had an event: ${{ github.event_name }} which trigged this {{STATUS}}!'
          include-details: false
          color-failure: 'eb4034'
